config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'searches' => "users#searches"
  end

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
  relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
       render :edit
    end
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォローされた一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

  def searches
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
     create_at = params[:created_at]
     @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%= user.followings.count %></td>
        <td>フォロワー数<%= user.followers.count %></td>
        <td>
          <% unless user.id == current_user.id %>
            <% if current_user.following?(user) %>
              <%= link_to "フォローを外す",user_relationships_path(user.id),method: :delete %>
            <% else %>
              <%= link_to "フォローする",user_relationships_path(user.id),method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_followings_path(user.id) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>follower</th>
    <th>
      <%= link_to user_followers_path(user.id) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>
<div class="row">
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to "フォローを外す",user_relationships_path(user.id),method: :delete,class: "btn btn-primary" %>
    <% else %>
      <%= link_to "フォローする",user_relationships_path(user.id),method: :post,class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>

app/views/users/_searches.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= render 'layouts/errors', obj: @user %>
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followings.html.erb
<div class='container'>
  <div class="row">
    <h2>Follow Users</h2>
      <% if users.exists? %>
        <table class ="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= @users.each |user| do %>
            <tr>
              <td><%= f.user.get_profile_image,size:'50x50' %></td>
              <td><%= f.user :name %></td>
              <td>フォロー数<%= f.user.followings.count %></td>
              <td>フォロワー数<%= f.user.followers.count %></td>
              <td></td>
              <td><%= link_to "Show",user_path(user.id) %></td>
            </tr>
          </tbody>
        </table>
      <% else %>
        <h4>ユーザーはいません</h4>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
  
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/searches.js.erb
$("#search_result").html("<%= j(render "searches", search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= form_with url: user_searches_path(@user),method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit "検索",class: "btn btn-info" %>
      <% end %>
      <div id="search_result">
        <% if @search_book.present? %>
          <%= render "searches", search_book: @search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>