config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'searches' => "users#searches"
  end

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @word = params[:word]
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<% if @range == "User" %>
    <h2>User search for "<%= @word %>"</h2>
    <table class="table">
      <% @users.each do |user| %>
        <tbody>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Introduction</th>
          </tr>
          <tr>
            <td><%= image_tag user.get_profile_image, size:'100x100' %></td>
            <td>
              <%= link_to user_path(user.id) do %>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.introduction %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
<% else %>
  <h2>Book search for "<%= @word %>" </h2>
  <table class="table">
    <% @books.each do |book| %>
      <tbody>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
          <tr>
            <td><%= image_tag book.user.get_profile_image, size:'80x80' %></td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
              </td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
<% end %>